### ISSUE TITLE
Feature: add datacenter and region labels

### ISSUE THREAD

**Issue by itatabitovski** [Nomon/nomad-exporter#3]
It would be nice to have datacenter and region labels to the running allocations.

**Comment by Nomon** [comment]
Good idea, I had no need for these myself as I added them via relabel configs from the __consul_meta_dc info from the prometheus consul discovery.

**Comment by itatabitovski** [comment]
Yes that is how I solved it for the datacenter, but it doesn't work for a region unless you name your datacenters something like "region-dc".

I will try to make a PR.
